### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by AlexVanderbist** [renoki-co/octane-exporter#11]
Hi!

Is there any chance you can share a Grafana dashboard for these Prometheus metrics?

Thanks

**Comment by rennokki** [comment]
@AlexVanderbist Hi there. Currently, I have none that I can share, but what you can do is to try Grafana's Metrics Explorer when creating new panels. 😥 Most of the metrics are made for the `rate()` aggregator function. The same applies to the Horizon metrics.

**Comment by AlexVanderbist** [comment]
No worries, I'll do that. Thanks for the advice!

**Comment by erfanmola** [comment]
Any dashboards to share ? :p
