### ISSUE TITLE
[IDEA] Add memory watcher?

### ISSUE THREAD

**Issue by Atomzwieback** [renoki-co/octane-exporter#16]
Hi,

first thx for the exporter, second i would like to ask if it would be an idea to add somehow a memory monitoring due octane is a bit more subsceptible for memory leaks?

**Comment by rennokki** [comment]
There is already one: https://github.com/renoki-co/octane-exporter/blob/master/src/Metrics/OctaneMemoryUsage.php ?

**Comment by nickkuijpers** [comment]
Hi,

Where should i put this Memory metric? At what listeners?

Thank you for creating the package!

**Comment by rennokki** [comment]
The memory metric - nowhere. It should be already registered if you add the listeners in your octane config? https://github.com/renoki-co/octane-exporter#-installation

**Comment by nickkuijpers** [comment]
Hi!

Ah i see, im sorry. Its working!
